"""Журнал знает автора и адрес, у поста появился паспорт

Журнал писался, но прочитать его было нечем: эндпоинта и страницы не существовало,
таблица просто росла. Хуже того, запись не помнила ни кто действовал, ни откуда, ни в
какой теме — на вопрос «кто одобрил этот пост» ответа не было. Добавлены
actor_admin_username (вход в панель по логину), actor_ip (за nginx — адрес человека, а
не контейнера) и theme_id, плюс индекс по дате: журнал читают лентой «последние
сверху».

post_passports — ответ на вопрос «почему вышел именно такой пост». Система принимает
на каждый пост несколько решений (какой был скор и какой порог он проходил, какой
персоной писали, к какой подтеме отнесли, что поправил редактор, куда уехало), и до
сих пор ни одно из них не сохранялось: всё уходило в логи, а человеку доставалась
карточка с текстом. Одно поле JSONB, потому что набор фактов будет меняться с каждой
правкой конвейера; отдельная таблица, потому что кандидаты читаются сотнями на каждой
странице очереди, а паспорт открывают по одному и по требованию.

Новые значения журнала (GENERATE, EDIT, UNAPPROVE, REJECT_ALL, RESTORE) добавляются
отдельными ALTER TYPE: автогенерация alembic новых членов enum в Postgres не замечает.

Revision ID: 0f86175ffdef
Revises: 66580b628cb0
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f86175ffdef'
down_revision: Union[str, None] = '66580b628cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ADD VALUE IF NOT EXISTS работает в транзакции в PG 12+, пока новое значение не
    # используется в той же транзакции (здесь не используется). Имена ЗАГЛАВНЫМИ:
    # SQLAlchemy пишет в enum имя члена, а не его значение.
    for value in ("GENERATE", "EDIT", "UNAPPROVE", "REJECT_ALL", "RESTORE"):
        op.execute(f"ALTER TYPE auditaction ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_passports',
    sa.Column('candidate_post_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_passports_candidate_post_id'), 'post_passports', ['candidate_post_id'], unique=True)
    op.add_column('audit_logs', sa.Column('actor_admin_username', sa.String(length=150), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_ip', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('theme_id', sa.UUID(), nullable=True))
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_theme_id'), 'audit_logs', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Удаление значений из enum PostgreSQL не поддерживает — оставляем как есть.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_theme_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_column('audit_logs', 'theme_id')
    op.drop_column('audit_logs', 'actor_ip')
    op.drop_column('audit_logs', 'actor_admin_username')
    op.drop_index(op.f('ix_post_passports_candidate_post_id'), table_name='post_passports')
    op.drop_table('post_passports')
    # ### end Alembic commands ###
