"""Учёт расходов на ИИ и настройки поведения

Расход на модель нигде не сохранялся: клиент считал токены и выбрасывал их. Ответить
«сколько ушло за вчера и на что» было нечем, и когда планировщик без ограничителей ушёл
в непрерывный рерайт, узнали об этом по счёту от провайдера, а не из панели.

llm_usage — строка на каждое обращение к модели: раздел работы, модель, токены (вход,
выход, чтение и запись кэша отдельно — у них разные тарифы, и без разделения расход
темы, которая переписывает посты пачкой, завышался бы в разы) и посчитанная на месте
стоимость. Стоимость сохраняется, а не пересчитывается на лету: тарифы провайдера
меняются, и вчерашние расходы должны остаться вчерашними.

panel_settings.automation — пороги и времена поведения одним JSONB. Первыми туда
ложатся дневной потолок расходов и процент предупреждения; дальше переедут константы
из кода. Не колонками: набор полей меняется с каждой задачей, которая трогает
поведение, и заводить миграцию под каждое число — работа без смысла. NULL означает
«все значения по умолчанию», поэтому система работает и до первого захода в настройки.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66580b628cb0'
down_revision: Union[str, None] = 'b3d5e91c47af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('kind', sa.Enum('REWRITE', 'CLASSIFY_RUBRIC', 'SUGGEST_RUBRICS', 'DISCOVERY', 'DIGEST', 'STYLE_EXTRACT', 'PERSONA_PREVIEW', name='llmusagekind'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_usage_created_at', 'llm_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_kind'), 'llm_usage', ['kind'], unique=False)
    op.create_index(op.f('ix_llm_usage_theme_id'), 'llm_usage', ['theme_id'], unique=False)
    op.add_column('panel_settings', sa.Column('automation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_settings', 'automation')
    op.drop_index(op.f('ix_llm_usage_theme_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_kind'), table_name='llm_usage')
    op.drop_index('ix_llm_usage_created_at', table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
