"""initial schema

Revision ID: fe24d8f8f3a0
Revises:
Create Date: 2026-07-21 09:27:16.891288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe24d8f8f3a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector/pgvector:pg16 делает расширение доступным, но не включает его в
    # конкретной базе автоматически — без этого candidate_posts.embedding
    # (VECTOR(1024)) ниже падает "type vector does not exist" на чистой БД.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('actor_tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('INGEST', 'SCORE', 'DEDUP_MERGE', 'REWRITE', 'PUBLISH', 'REJECT', 'AD_DETECTED', 'AD_COVERED', 'SETTINGS_CHANGE', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('panel_settings',
    sa.Column('panel_title', sa.String(length=255), nullable=False),
    sa.Column('accent_color', sa.String(length=16), nullable=False),
    sa.Column('logo_image', sa.LargeBinary(), nullable=True),
    sa.Column('logo_content_type', sa.String(length=64), nullable=True),
    sa.Column('anthropic_api_key_override', sa.Text(), nullable=False),
    sa.Column('voyage_api_key_override', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telethon_sessions',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('session_string', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telethon_sessions_is_active'), 'telethon_sessions', ['is_active'], unique=False)
    op.create_table('themes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_style_prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_themes_is_active'), 'themes', ['is_active'], unique=False)
    op.create_table('channel_bots',
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('THEME', 'ADMIN', name='botrole'), nullable=False),
    sa.Column('bot_token', sa.Text(), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('cadence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_bots_is_active'), 'channel_bots', ['is_active'], unique=False)
    op.create_index(op.f('ix_channel_bots_role'), 'channel_bots', ['role'], unique=False)
    op.create_table('pool_posts',
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'GENERATED', 'RECYCLED_CANDIDATE', name='poolpostsource'), nullable=False),
    sa.Column('status', sa.Enum('READY', 'USED', name='poolpoststatus'), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_posts_status'), 'pool_posts', ['status'], unique=False)
    op.create_index(op.f('ix_pool_posts_theme_id'), 'pool_posts', ['theme_id'], unique=False)
    op.create_table('target_channels',
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_channels_is_active'), 'target_channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_target_channels_tg_chat_id'), 'target_channels', ['tg_chat_id'], unique=True)
    op.create_index(op.f('ix_target_channels_theme_id'), 'target_channels', ['theme_id'], unique=False)
    op.create_table('source_channels',
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.Column('ingest_session_id', sa.UUID(), nullable=True),
    sa.Column('last_scanned_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_session_id'], ['telethon_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_chat_id'),
    sa.UniqueConstraint('tg_username')
    )
    op.create_index(op.f('ix_source_channels_is_active'), 'source_channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_source_channels_theme_id'), 'source_channels', ['theme_id'], unique=False)
    op.create_table('candidate_posts',
    sa.Column('source_channel_id', sa.UUID(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SCORING', 'SELECTED', 'REWRITTEN', 'QUEUED', 'PUBLISHED', 'REJECTED', 'DUPLICATE', name='candidatepoststatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('selected_post_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['candidate_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_channel_id'], ['source_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_channel_id', 'tg_message_id', name='uq_candidate_source_channel_message')
    )
    op.create_index(op.f('ix_candidate_posts_status'), 'candidate_posts', ['status'], unique=False)
    op.create_table('post_versions',
    sa.Column('candidate_post_id', sa.UUID(), nullable=False),
    sa.Column('variant_no', sa.Integer(), nullable=False),
    sa.Column('rewritten_text', sa.Text(), nullable=False),
    sa.Column('persona_prompt_used', sa.Text(), nullable=False),
    sa.Column('source_similarity', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_candidate_posts_selected_post_version_id', 'candidate_posts', 'post_versions', ['selected_post_version_id'], ['id'], ondelete='SET NULL')
    op.create_table('candidate_metrics_snapshots',
    sa.Column('candidate_post_id', sa.UUID(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('forwards', sa.BigInteger(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_metrics_snapshots_candidate_post_id'), 'candidate_metrics_snapshots', ['candidate_post_id'], unique=False)
    op.create_table('publications',
    sa.Column('target_channel_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('CANDIDATE', 'POOL', name='publicationsource'), nullable=False),
    sa.Column('post_version_id', sa.UUID(), nullable=True),
    sa.Column('pool_post_id', sa.UUID(), nullable=True),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_ad_cover', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_post_id'], ['pool_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_version_id'], ['post_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_channel_id'], ['target_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_target_channel_id'), 'publications', ['target_channel_id'], unique=False)
    op.create_table('ad_detections',
    sa.Column('target_channel_id', sa.UUID(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('PENDING', 'AUTO_BURIED', 'IGNORED', name='addetectionaction'), nullable=False),
    sa.Column('covering_publication_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['covering_publication_id'], ['publications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_channel_id'], ['target_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_detections_action'), 'ad_detections', ['action'], unique=False)
    op.create_index(op.f('ix_ad_detections_target_channel_id'), 'ad_detections', ['target_channel_id'], unique=False)
    op.create_table('publication_metrics_snapshots',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('forwards', sa.BigInteger(), nullable=True),
    sa.Column('reactions', sa.BigInteger(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_metrics_snapshots_publication_id'), 'publication_metrics_snapshots', ['publication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_metrics_snapshots_publication_id'), table_name='publication_metrics_snapshots')
    op.drop_table('publication_metrics_snapshots')
    op.drop_index(op.f('ix_ad_detections_target_channel_id'), table_name='ad_detections')
    op.drop_index(op.f('ix_ad_detections_action'), table_name='ad_detections')
    op.drop_table('ad_detections')
    op.drop_index(op.f('ix_publications_target_channel_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_candidate_metrics_snapshots_candidate_post_id'), table_name='candidate_metrics_snapshots')
    op.drop_table('candidate_metrics_snapshots')
    op.drop_constraint('fk_candidate_posts_selected_post_version_id', 'candidate_posts', type_='foreignkey')
    op.drop_table('post_versions')
    op.drop_index(op.f('ix_candidate_posts_status'), table_name='candidate_posts')
    op.drop_table('candidate_posts')
    op.drop_index(op.f('ix_source_channels_theme_id'), table_name='source_channels')
    op.drop_index(op.f('ix_source_channels_is_active'), table_name='source_channels')
    op.drop_table('source_channels')
    op.drop_index(op.f('ix_target_channels_theme_id'), table_name='target_channels')
    op.drop_index(op.f('ix_target_channels_tg_chat_id'), table_name='target_channels')
    op.drop_index(op.f('ix_target_channels_is_active'), table_name='target_channels')
    op.drop_table('target_channels')
    op.drop_index(op.f('ix_pool_posts_theme_id'), table_name='pool_posts')
    op.drop_index(op.f('ix_pool_posts_status'), table_name='pool_posts')
    op.drop_table('pool_posts')
    op.drop_index(op.f('ix_channel_bots_role'), table_name='channel_bots')
    op.drop_index(op.f('ix_channel_bots_is_active'), table_name='channel_bots')
    op.drop_table('channel_bots')
    op.drop_index(op.f('ix_themes_is_active'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_telethon_sessions_is_active'), table_name='telethon_sessions')
    op.drop_table('telethon_sessions')
    op.drop_table('panel_settings')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
